set(RESOURCE_DLL_PRODUCT_NAME "Plv Player SDK")
set(RESOURCE_COMPANY_NAME "")
set(RESOURCE_COMPANY_NAME_ZH_CN "")
set(RESOURCE_LEGAL_COPYRIGHT "")
set(RESOURCE_LEGAL_COPYRIGHT_ZH_CN "")


set(DLL_RESOURCE_COMPANY_NAME ${RESOURCE_COMPANY_NAME})
set(DLL_RESOURCE_FILE_DESCRIPTION ${RESOURCE_DLL_PRODUCT_NAME})
set(DLL_RESOURCE_LEGAL_COPYRIGHT ${RESOURCE_LEGAL_COPYRIGHT})
set(DLL_RESOURCE_PRODUCT_NAME ${RESOURCE_DLL_PRODUCT_NAME})

set(RESOURCE_DEMO_PRODUCT_NAME_ZH_CN "POLYV 点播助手")
set(RESOURCE_DEMO_PRODUCT_NAME "POLYV 点播助手")


if(MSVC)
	set(DEMO_RESOURCE_COMPANY_NAME ${RESOURCE_COMPANY_NAME})
	set(DEMO_RESOURCE_FILE_DESCRIPTION ${RESOURCE_DEMO_PRODUCT_NAME})
	set(DEMO_RESOURCE_LEGAL_COPYRIGHT ${RESOURCE_LEGAL_COPYRIGHT})
	set(DEMO_RESOURCE_PRODUCT_NAME ${RESOURCE_DEMO_PRODUCT_NAME})
elseif(APPLE)
	set(MACOSX_BUNDLE_BUNDLE_NAME ${RESOURCE_DEMO_PRODUCT_NAME})
	set(MACOSX_BUNDLE_BUNDLE_DISPLAY_NAME ${RESOURCE_DEMO_PRODUCT_NAME})
	set(MACOSX_BUNDLE_BUNDLE_VERSION ${PLV_PLAYER_SDK_VERSION})
	set(MACOSX_BUNDLE_SHORT_VERSION_STRING ${PLV_PLAYER_SDK_VERSION})
	set(MACOSX_BUNDLE_GUI_IDENTIFIER "net.polyv.PC-plv-player")
endif()
